import { defineCollection, defineContentConfig, z } from '@nuxt/content'
import { partSchema, chassisSchema } from './shared/catalog/schema.ts'

export default defineContentConfig({
  collections: {
    // Guides, about and other prose pages. This matches Markdown only, so the
    // generated catalog YAML below never lands in it.
    content: defineCollection({
      type: 'page',
      source: '**/*.md',
      schema: z.object({
        description: z.string().optional()
      })
    }),

    // Generated by scripts/catalog/generate.ts — never hand-edit these files;
    // corrections belong in data/overrides/parts.yml.
    parts: defineCollection({
      type: 'data',
      source: 'parts/**.yml',
      schema: partSchema
    }),

    chassis: defineCollection({
      type: 'data',
      source: 'chassis/**.yml',
      schema: chassisSchema
    })
  }
})
