import { defineCollection, defineContentConfig, z } from '@nuxt/content'
import { partSchema, chassisSchema, kitSchema } from './shared/catalog/schema.ts'

const pageSchema = z.object({
  description: z.string().optional()
})

export default defineContentConfig({
  collections: {
    // Guides, about and other prose pages, one collection per locale. Both
    // match Markdown only, so the generated catalog YAML below never lands in
    // them — and keep the `.md` in the glob, or any YAML that ever appears
    // under a locale directory would be parsed as a page and fail this schema.
    //
    // `prefix` is what each collection's paths are rewritten to. It is
    // load-bearing on both: left to its default it is derived from the static
    // head of the include glob and then lowercased, so zh-Hant/about/index.md
    // would land on /zh-hant/about and never match a route.
    contentZhHant: defineCollection({
      type: 'page',
      // The default locale is served unprefixed, so its pages are /about etc.
      source: { include: 'zh-Hant/**/*.md', prefix: '/' },
      schema: pageSchema
    }),

    // '/en' is the public route prefix too, so document paths equal route.path
    // verbatim and [...slug].vue looks pages up by the raw route in both
    // locales. Collection names become SQLite table names and are checked
    // against /^[a-z_]\w*$/i, so no hyphens.
    contentEn: defineCollection({
      type: 'page',
      source: { include: 'en/**/*.md', prefix: '/en' },
      schema: pageSchema
    }),

    // Generated by scripts/catalog/generate.ts — never hand-edit these files;
    // corrections belong in data/overrides/parts.yml.
    parts: defineCollection({
      type: 'data',
      source: 'parts/**.yml',
      schema: partSchema
    }),

    chassis: defineCollection({
      type: 'data',
      source: 'chassis/**.yml',
      schema: chassisSchema
    }),

    kits: defineCollection({
      type: 'data',
      source: 'kits/**.yml',
      schema: kitSchema
    })
  }
})
